#
#  Author: Nho Luong
#  Date: 2020-03-13 21:10:39 +0000 (Fri, 13 Mar 2020)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/nholuongut/dockerfiles
#
#  License: see accompanying Nho Luong LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#


# ============================================================================ #
#                B i t b u c k e t   C I / C D   P i p e l i n e
# ============================================================================ #

# Reference:
#
#   https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/

# Languages:
#
#   https://confluence.atlassian.com/x/5Q4SMw

# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  default:
    - step:
        script:
          - setup/ci_bootstrap.sh
          - make init
          - make ci
          - make test
