#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Nho Luong
#  Date: 2020-03-13 21:10:39 +0000 (Fri, 13 Mar 2020)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/nholuongut/dockerfiles
#
#  License: see accompanying Nho Luong LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#

version: '3'
services:
  cassandra:
    image: nholuongut/cassandra-dev:${VERSION:-latest}
    ports:
      - 7199:7199
      - 9042:9042
      - 9160:9160
