#
#  Author: Nho Luong
#  Date: 2020-03-13 21:10:39 +0000 (Fri, 13 Mar 2020)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/nholuongut/dockerfiles
#
#  License: see accompanying Nho Luong LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#

# ============================================================================ #
#                                C i r c l e C I
# ============================================================================ #

# Master Template with more advanced config:
#
#   https://github.com/nholuongut/Templates/blob/master/circleci_config.yml

# Reference:
#
#   https://circleci.com/docs/2.0/configuration-reference

version: 2.1

workflows:
  version: 2
  workflow:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run: setup/ci_bootstrap.sh
      - run: make init
      - run: make
      - run: make test
