#
#  Author: Nho Luong
#  Date: 2020-03-13 21:10:39 +0000 (Fri, 13 Mar 2020)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/nholuongut/dockerfiles
#
#  License: see accompanying Nho Luong LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
FROM nholuongut/centos-java:latest

ARG TEAMCITY_VERSION=10.0

ENV PATH $PATH:/opt/TeamCity/bin
LABEL maintainer="Nho Luong <luongutnho@hotmail.com>"
LABEL org.opencontainers.image.description="Nho Luong" \
      org.opencontainers.image.version="$NhoLuong_VERSION" \
      org.opencontainers.image.authors="Nho Luong (https://www.linkedin.com/in/nholuong)" \
      org.opencontainers.image.documentation="https://hub.docker.com/u/nholu" \
      org.opencontainers.image.source="https://github.com/nholuongut/dockerfiles"

ARG TAR="TeamCity-$TEAMCITY_VERSION.tar.gz"

WORKDIR /opt

RUN set -eux && \
    yum install -y tar && \
    curl -L "https://download.jetbrains.com/teamcity/$TAR" > "$TAR" && \
    tar zxf "$TAR" && \
    # fails as it tries to remove systemd
    #yum remove -y tar && \
    yum autoremove -y && \
    yum clean all && \
    rm -rf /var/cache/yum

EXPOSE 8111

CMD ["teamcity-server.sh", "start"]
