#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Nho Luong
#  Date: 2020-03-13 21:10:39 +0000 (Fri, 13 Mar 2020)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/nholuongut/dockerfiles
#
#  License: see accompanying Nho Luong LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#

version: '3'
services:
  hadoop:
    image: nholuongut/hadoop:${VERSION:-latest}
    ports:
      #- 8020:8020
      - 8042:8042
      - 8088:8088
      #- 9000:9000
      - 9864:9864
      - 9870:9870
      #- 10020:10020
      - 19888:19888
      - 50010:50010
      - 50020:50020
      - 50070:50070
      - 50075:50075
      - 50090:50090
