#  vim:ts=2:sts=2:sw=2:et
#
#
#  Author: Nho Luong
#  Date: 2020-03-13 21:10:39 +0000 (Fri, 13 Mar 2020)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/nholuongut/dockerfiles
#
#  License: see accompanying Nho Luong LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#

version: '3'
services:
  hbase-master:
    image: nholuongut/hbase:${VERSION:-latest}
    command: master
    ports:
      - 16000:16000
      - 16010:16010
  hbase-regionserver:
    image: nholuongut/hbase:${VERSION:-latest}
    command: regionserver
    ports:
      - 16030:16030
      - 16201:16201
      - 16301:16301
  hbase-thrift:
    image: nholuongut/hbase:${VERSION:-latest}
    command: thrift
    ports:
      - 9090:9090
      - 9095:9095
  hbase-stargate:
    image: nholuongut/hbase:${VERSION:-latest}
    command: stargate
    ports:
      - 8080:8080
      - 8085:8085
  zookeeper:
    image: nholuongut/zookeeper:latest
    ports:
      - 2181:2181
