#
#  Author: Nho Luong
#  Date: 2020-03-13 21:10:39 +0000 (Fri, 13 Mar 2020)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/nholuongut/dockerfiles
#
#  License: see accompanying Nho Luong LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
---
options:
  dynamic_substitutions: true
substitutions:
  _IMAGE_NAME: git-kustomize
  _IMAGE_VERSION: "4.4"  # XXX: must override this, eg. "gcloud builds submit --substitutions=_IMAGE_VERSION:4.5"
  _REGISTRY: europe-docker.pkg.dev
  _REPOSITORY: git-kustomize
  _PROJECT: $CLOUDSDK_CORE_PROJECT
  _IMAGE: ${_REGISTRY}/${_PROJECT}/${_REPOSITORY}/${_IMAGE_NAME}

timeout: 660s

images:
  - ${_REGISTRY}/${_PROJECT}/${_REPOSITORY}/${_IMAGE_NAME}

steps:
  - id: pull-image-cache-latest
    name: gcr.io/cloud-builders/docker
    waitFor: ['-']
    entrypoint: 'bash'
    args:
      - -c
      - docker pull ${_IMAGE}:latest || exit 0

  - id: pull-image-cache-version
    name: gcr.io/cloud-builders/docker
    waitFor: ['-']
    entrypoint: 'bash'
    args:
      - -c
      - docker pull ${_IMAGE}:${_IMAGE_VERSION} || exit 0

  - id: build-git-kustomize
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=${_IMAGE}:latest
      - --tag=${_IMAGE}:${_IMAGE_VERSION}
      - --build-arg=BUILDKIT_INLINE_CACHE=1
      - --cache-from=${_IMAGE}:latest
      - --cache-from=${_IMAGE}:${_IMAGE_VERSION}
      - .
    timeout: 600s
