#
#  Author: Nho Luong
#  Date: 2020-03-13 21:10:39 +0000 (Fri, 13 Mar 2020)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/nholuongut/dockerfiles
#
#  License: see accompanying Nho Luong LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#

# ============================================================================ #
#                               F o r k   S y n c
# ============================================================================ #

# For a fork of the original repo, activate to keep it up to date via straight GitHub sync to the default branch

---
name: Fork Sync

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 */3 * * *'

permissions:
  contents: write

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  fork_sync:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == true
    if: github.repository_owner != 'nholuongut'
    name: Fork Sync
    uses: nholuongut/GitHub-Actions/.github/workflows/fork-sync.yaml@master
    with:
      debug: ${{ github.event.inputs.debug }}
